#src/app/config/routing.yml
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Aqui es dnd se indica la raiz del sitio, llamado al controller que ejecute la indexAction que llama 'default/app_index.html.twig'
index:   
  path: /  
  defaults: { _controller: AppBundle:Default:index } 


app_yml:
    resource: "@AppBundle/Resources/Config/routing.yml"
#   prefix:   /T5b
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}/ 
    # Para la internacionalizacion del bundle Actv1 T10
