#src/app/config/routing.yml
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

index:   
  path: /  
  defaults: { _controller: AppBundle:Default:index } 
  requeriments:
     _locale: es|en   # esto es una expresion regular que puede tomar valores es o en, de momento

app_yml:
    resource: "@AppBundle/Resources/Config/routing.yml"
#   prefix:   /T5b
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /{_locale}/ # Para la internacionalizacion del bundle Actv1 T10