# app/config/security.yml
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  
        encoders:
            # Como ahora lo hacemos con el FOS, lo debo incluir    
            FOS\UserBundle\Model\UserInterface: bcrypt
            
        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN
    
        providers:
            fos_userbundle:
                #id: fos_user.user_provider.username
                # Cambio el user provider para usar el username o el email indistintamente para logarme
                # para el paso b) T8 actv 2
                id: fos_user.user_provider.username_email
    
        firewalls:
            main:
                pattern: ^/
                form_login:
                    provider: fos_userbundle
                    csrf_token_generator: security.csrf.token_manager        
                    # if you are using Symfony < 2.8, use the following config instead:
                    # csrf_provider: form.csrf_provider
    
                logout:       true
                anonymous:    true
    
        access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }
            - { path: ^/T5b/admin, roles: ROLE_ADMIN }
            - { path: ^/T5b/product/list, roles: ROLE_APP_ADMIN }
            - { path: ^/T5b/product/list, roles: ROLE_USER }
            - { path: ^/T5b/product/edit, roles: ROLE_APP_ADMIN }
            - { path: ^/T5b/product/delete, roles: ROLE_APP_ADMIN }
            - { path: ^/T5b/category/list, roles: ROLE_APP_ADMIN }
            - { path: ^/T5b/category/list, roles: ROLE_USER }
            - { path: ^/T5b/category/edit, roles: ROLE_APP_ADMIN }
            - { path: ^/T5b/category/delete, roles: ROLE_APP_ADMIN }    