# app/config/security.yml
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
  
        encoders:
            # Como ahora lo hacemos con el FOS, lo debo incluir    
            FOS\UserBundle\Model\UserInterface: bcrypt
            
        role_hierarchy:
           ROLE_ADMIN:       ROLE_USER, ROLE_APP_ADMIN
           ROLE_SUPER_ADMIN: ROLE_ADMIN
    
        providers:
            fos_userbundle:
                #id: fos_user.user_provider.username
                # Cambio el user provider para usar el username o el email indistintamente para logarme
                # para el paso b) T8 actv 2
                id: fos_user.user_provider.username_email
    
        firewalls:
            main:
                pattern: ^/
                anonymous: true
                logout:       
                  path: fos_user_security_logout
                form_login:
                    provider: fos_userbundle
                    csrf_token_generator: security.csrf.token_manager       
                    # Para la internazionalizacion de la actv1 T10 (logi_path y check_path)
                    login_path: fos_user_security_login
                    check_path: fos_user_security_check 
                    # if you are using Symfony < 2.8, use the following config instead:
                    # csrf_provider: form.csrf_provider
                
    
        # pongo la expresion regular /[a-z]+ al principio de cada ruta para aceptar la es y la en, de momento
        access_control:
            - { path: ^/[a-z]+/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[a-z]+/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[a-z]+/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/[a-z]+/admin/, role: ROLE_ADMIN }
            - { path: ^/[a-z]+/admin, roles: ROLE_ADMIN }
            - { path: ^/[a-z]+/product/createStatic, roles: [ROLE_ADMIN] }
            - { path: ^/[a-z]+/product/createParam, roles: [ROLE_ADMIN] }
            - { path: ^/[a-z]+/product/newProduct, roles: [ROLE_ADMIN] }
            - { path: ^/[a-z]+/product/list, roles: [ROLE_USER] }
            - { path: ^/[a-z]+/product/show, roles: [ROLE_USER] }
            - { path: ^/[a-z]+/product/edit, roles: [ROLE_APP_ADMIN] }
            - { path: ^/[a-z]+/product/delete, roles: [ROLE_APP_ADMIN] }
            - { path: ^/[a-z]+/category/create, roles: [ROLE_APP_ADMIN] }
            - { path: ^/[a-z]+/category/new, roles: [ROLE_APP_ADMIN] }
            - { path: ^/[a-z]+/category/list, roles: [ROLE_USER] }
            - { path: ^/[a-z]+/category/edit, roles: [ROLE_APP_ADMIN] }
            - { path: ^/[a-z]+/category/delete, roles: [ROLE_APP_ADMIN] }
            - { path: ^/[a-z]+/person/new, roles: [ROLE_APP_ADMIN] }
            - { path: ^/[a-z]+/person/list, roles: [ROLE_USER] }
            - { path: ^/[a-z]+/person/show, roles: [ROLE_USER] }
            - { path: ^/[a-z]+/person/delete, roles: [ROLE_APP_ADMIN] }
                      
           
        
            